'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.6060
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.6060.
'
Namespace ts01
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://services.medscreen.com/")>  _
    Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://ts01/Solutions/WebService1/Service1.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.medscreen.com/CheckPassword", RequestNamespace:="http://services.medscreen.com/", ResponseNamespace:="http://services.medscreen.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckPassword(ByVal UserName As String, ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("CheckPassword", New Object() {UserName, Password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginCheckPassword(ByVal UserName As String, ByVal Password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CheckPassword", New Object() {UserName, Password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCheckPassword(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.medscreen.com/CheckEncryptedPassword", RequestNamespace:="http://services.medscreen.com/", ResponseNamespace:="http://services.medscreen.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckEncryptedPassword(ByVal UserName As String, ByVal Password As String) As String
            Dim results() As Object = Me.Invoke("CheckEncryptedPassword", New Object() {UserName, Password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginCheckEncryptedPassword(ByVal UserName As String, ByVal Password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CheckEncryptedPassword", New Object() {UserName, Password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndCheckEncryptedPassword(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
