'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.6060
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.6060.
'
Namespace ts011
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CardiffServiceSoap", [Namespace]:="http://concateno.com/Cardiff")>  _
    Public Class CardiffService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://ts01/CardiffSoap/service1.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://concateno.com/Cardiff/GetReceivedSamples", RequestNamespace:="http://concateno.com/Cardiff", ResponseNamespace:="http://concateno.com/Cardiff", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetReceivedSamples(ByVal FromDate As Date, ByVal stylesheet As String) As String
            Dim results() As Object = Me.Invoke("GetReceivedSamples", New Object() {FromDate, stylesheet})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetReceivedSamples(ByVal FromDate As Date, ByVal stylesheet As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetReceivedSamples", New Object() {FromDate, stylesheet}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetReceivedSamples(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://concateno.com/Cardiff/GetReceivedSamplesBySMIDProfile", RequestNamespace:="http://concateno.com/Cardiff", ResponseNamespace:="http://concateno.com/Cardiff", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetReceivedSamplesBySMIDProfile(ByVal FromDate As Date, ByVal SMIDProfile As String, ByVal stylesheet As String) As String
            Dim results() As Object = Me.Invoke("GetReceivedSamplesBySMIDProfile", New Object() {FromDate, SMIDProfile, stylesheet})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetReceivedSamplesBySMIDProfile(ByVal FromDate As Date, ByVal SMIDProfile As String, ByVal stylesheet As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetReceivedSamplesBySMIDProfile", New Object() {FromDate, SMIDProfile, stylesheet}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetReceivedSamplesBySMIDProfile(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://concateno.com/Cardiff/GetReceivedSamplesByCM", RequestNamespace:="http://concateno.com/Cardiff", ResponseNamespace:="http://concateno.com/Cardiff", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetReceivedSamplesByCM(ByVal CM As String, ByVal stylesheet As String) As String
            Dim results() As Object = Me.Invoke("GetReceivedSamplesByCM", New Object() {CM, stylesheet})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginGetReceivedSamplesByCM(ByVal CM As String, ByVal stylesheet As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetReceivedSamplesByCM", New Object() {CM, stylesheet}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetReceivedSamplesByCM(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
